name: ambo_benchmark
channels:
  - conda-forge
  - defaults
dependencies:
  - fbprophet=0.5
  - jupyterlab=1.2.6
  - nbconvert=5.6.1
  - pip=20.0.2
  - plotly=4.3.0
  - python=3.7.5
  - statsmodels=0.11.0
  - pip:
    - forecast-tools==0.1.5
    - numpy==1.19.5
    - pandas==1.2.1
    - pmdarima==1.5.2
    - scipy==1.6.0
    - seaborn==0.11.1
    - tbats==1.0.10
